dist: xenial

language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"

env:
  - DJANGO="django>=3.2,<3.3"
  - DJANGO="django>=4.0,<4.1"

before_install:
  - export PYTHONPATH=$HOME/builds/slyapustin/django-classified
  - export PIP_USE_MIRRORS=true

install:
  - pip install $DJANGO --quiet
  - python setup.py install
  - pip install flake8
  - pip install coverage

before_script:
  - flake8

script:
  - coverage run --source='.' quicktest.py django_classified

after_success:
  - coverage report --show-missing
